server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

pg-simulator:
  payment:
    callback-url: http://localhost:8080/api/v1/payments/callback

resilience4j:
  retry:
    instances:
      pgRetry:
        max-attempts: 3 # 최초 요청 1회 + 재시도 2회 = 총 3번
        wait-duration: 1s # 재시도 간 기본 대기 시간 (첫 재시도 전 대기 시간)
        enable-exponential-backoff: true  # 지수 백오프 활성화 (재시도 시 대기 시간이 배수로 증가)
        exponential-backoff-multiplier: 2 # 지수 백오프 배수, 대기 시간이 1s → 2s → 4s 순으로 증가
        retry-exceptions:
          - feign.FeignException.InternalServerError
          - feign.RetryableException # 타임아웃 등 네트워크 예외도 모두 커버
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        ignore-exceptions:
          - feign.FeignException.BadRequest # 400 비즈니스 예외 무시
        fail-after-max-attempts: true # 최대 재시도 횟수 초과시 예외 발생 (재시도 실패 처리)

  circuitbreaker:
    instances:
      pgCircuit:
        sliding-window-type: count_based
        # 최근 10건을 관찰하지만, 7건 이상이 쌓인 시점부터 임계치 판정을 시작
        # 1~6건: 상태 판정 안 함, 7~10건: 판정 함, 11건 이후: 계속 최근 10건으로 판정
        sliding-window-size: 10 # 슬라이딩 윈도우 크기
        minimum-number-of-calls: 7 # 최소 호출 수
        failure-rate-threshold: 50 # 실패율이 50% 넘으면 Open
        slow-call-duration-threshold: 2s # 느린 호출로 간주되는 시간 (2초)
        slow-call-rate-threshold: 50 # 느린 호출 비율이 50% 넘으면 Open
        wait-duration-in-open-state: 2s # Open 상태 유지 시간
        permitted-number-of-calls-in-half-open-state: 1 # Half-Open 상태에서 허용되는 호출 수
        max-wait-duration-in-half-open-state: 1s # Half-Open 상태에서 최대 대기 시간

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false